from tacex_assets.robots.franka.franka_gsmini_gripper_uipc_high_res import (
    FRANKA_PANDA_ARM_GSMINI_GRIPPER_HIGH_PD_HIGH_RES_UIPC_CFG
)
from tacex_assets.robots.franka.franka_gf225_gripper_uipc import (
    FRANKA_PANDA_ARM_GF225_GRIPPER_HIGH_PD_HIGH_RES_UIPC_CFG
)
from tacex_assets.robots.franka.franka_zx_hand_gripper_uipc import (
    FRANKA_PANDA_ARM_ZX_HAND_HIGH_PD_CFG
)

from isaaclab.utils import configclass
from isaaclab.assets import ArticulationCfg
from tacex_assets import TACEX_ASSETS_DATA_DIR
from ..sensors.tactile import TactileCfg, create_tactile_cfg

@configclass
class RobotCfg:
    robot: ArticulationCfg = None
    tactiles: list[TactileCfg] = []

    gripper_offset: float = 0.131 # in m
    gripper_max_qpos: float = 0.039 # in m

    tactile_far_plane: float = 30.0 # in mm
    adaptive_grasp_depth_threshold: float = 27.5 # in mm, used for grasping
    contact_threshold: tuple[float, float] = (27.5, 28.0) # in mm, used in `gravity_rotate` api

def create_franka_gsmini_gripper(data_type:list[str]):
    robot = FRANKA_PANDA_ARM_GSMINI_GRIPPER_HIGH_PD_HIGH_RES_UIPC_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            joint_pos={
                "panda_joint1": 0.0,
                "panda_joint2": 0.0,
                "panda_joint3": 0.0,
                "panda_joint4": -2.46,
                "panda_joint5": 0.0,
                "panda_joint6": 2.5,
                "panda_joint7": 0.741,
                "panda_finger.*": 0.02,
            }
        ),
    )
    tactiles = [
        create_tactile_cfg(
            prim_path="/World/envs/env_.*/Robot/gelsight_mini_case_left",
            gelpad_prim_path="/World/envs/env_.*/Robot/gelpad_left",
            gelpad_attachment_body_name="gelsight_mini_case_left",
            name="left_tactile",
            sensor_type="gsmini",
            data_type=data_type,
        ),
        create_tactile_cfg(
            prim_path="/World/envs/env_.*/Robot/gelsight_mini_case_right",
            gelpad_prim_path="/World/envs/env_.*/Robot/gelpad_right",
            gelpad_attachment_body_name="gelsight_mini_case_right",
            name="right_tactile",
            sensor_type="gsmini",
            data_type=data_type,
        )
    ]
    return RobotCfg(
        robot=robot,
        tactiles=tactiles,
        gripper_offset=0.131,
        gripper_max_qpos=0.039,
        tactile_far_plane=34.0,
        adaptive_grasp_depth_threshold=27.5,
        contact_threshold=(27.5, 28.0)
    )

def create_franka_gf225_gripper(data_type:list[str]):
    robot = FRANKA_PANDA_ARM_GF225_GRIPPER_HIGH_PD_HIGH_RES_UIPC_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            joint_pos={
                "panda_joint1": 0.0,
                "panda_joint2": 0.0,
                "panda_joint3": 0.0,
                "panda_joint4": -2.46,
                "panda_joint5": 0.0,
                "panda_joint6": 2.5,
                "panda_joint7": 0.741,
                "panda_finger.*": 0.02,
            }
        ), 
    )
    tactiles = [
        create_tactile_cfg(
            prim_path="/World/envs/env_.*/Robot/GF225_left",
            gelpad_prim_path="/World/envs/env_.*/Robot/GF225_gelpad_left",
            gelpad_attachment_body_name="GF225_left",
            name="left_tactile",
            sensor_type="gf225",
            data_type=data_type,
        ),
        create_tactile_cfg(
            prim_path="/World/envs/env_.*/Robot/GF225_right",
            gelpad_prim_path="/World/envs/env_.*/Robot/GF225_gelpad_right",
            gelpad_attachment_body_name="GF225_right",
            name="right_tactile",
            sensor_type="gf225",
            data_type=data_type,
        )
    ]
    return RobotCfg(
        robot=robot,
        tactiles=tactiles,
        gripper_offset=0.131,
        gripper_max_qpos=0.039,
        tactile_far_plane=29.0,
        adaptive_grasp_depth_threshold=26.8,
        contact_threshold=(26.5, 27.0)
    )

def create_franka_zx_hand_gripper(data_type: list[str]):
    """Official Xense ZX hand on Franka, using official xensim tactile.

    No UIPC gel pad is attached.  The two tactile sensors are the rigid finger
    meshes `xense_leftfinger` / `xense_rightfinger`; the tactile images are
    generated by the official xensim `FemSensor` from orthographic finger
    cameras, matching the xense-sim4.5 `office_usb_insert.py` example.
    """
    robot = FRANKA_PANDA_ARM_ZX_HAND_HIGH_PD_CFG.replace(
        prim_path="/World/envs/env_.*/Robot",
        init_state=ArticulationCfg.InitialStateCfg(
            joint_pos={
                "panda_joint1": 0.0,
                "panda_joint2": 0.0,
                "panda_joint3": 0.0,
                "panda_joint4": -2.46,
                "panda_joint5": 0.0,
                "panda_joint6": 2.5,
                "panda_joint7": 0.741,
                # official ZX hand (cust_franka.py): open ~ pi/3, but USD caps the
                # joint at 1.0 rad (exclusive), so 0.99 = open, 0 = closed
                "right_Left_1_Joint": 0.99,
                "right_Right_1_Joint": 0.99,
            }
        ),
    )
    tactiles = [
        TactileCfg(
            name="left_tactile",
            sensor_type="zxhand",
            sensor_cfg={
                "finger_prim_path": "/World/envs/env_.*/Robot/xense_leftfinger",
                "side": "left",
            },
        ),
        TactileCfg(
            name="right_tactile",
            sensor_type="zxhand",
            sensor_cfg={
                "finger_prim_path": "/World/envs/env_.*/Robot/xense_rightfinger",
                "side": "right",
            },
        ),
    ]
    return RobotCfg(
        robot=robot,
        tactiles=tactiles,
        # ZX: virtual panda_hand + runtime-calibrated offset (see robot.setup()).
        gripper_offset=0.0,
        gripper_max_qpos=0.99,
        # Official ZX tactile: get_min_depth returns processed cam depth (mm),
        # resting (no contact) = +1.0 mm (clip max), full indentation = -4.0 mm.
        # far_plane must equal the resting value so adaptive grasp uses coarse
        # steps until contact, then fine steps to reach the contact threshold.
        tactile_far_plane=1.0,
        adaptive_grasp_depth_threshold=-1.5,
        contact_threshold=(-2.0, -1.5),
    )
